Subindo feature para develop
gustavoMarquesz/propig pull request #4
Opened 2023-04-01 19:22 UTC by gustavoMarquesz

Hello! subindo a feature... a página de login ia comportar login e cadastro na mesma página. 
Mas devido ao pensamento sobre regra de negócio, separei em duas. Porque? dividindo em páginas, temos espaço 
para dar um breve resumo de como e sobre o que se trata esta aplicação web e qual o produto que a empresa vende.

2023-04-01 21:22 UTC, marcosilva2336 approved these changes
Pagina de login feita por Gustavo

2023-04-01 22:20 UTC, marcosilva2336 commented on propig/src/pages/LoginPage.jsx
> +                    <h2>conecte se</h2>
Erro de pt-br.
Correção: Conecte-se

2023-04-01 22:23 UTC, marcosilva2336 requested changes

2023-04-01 22:23 UTC, marcosilva2336 commented on propig/src/pages/LoginPage.jsx
> +                    <h2>conecte se</h2>
Correção: Conecte-se

2023-04-01 22:33 UTC, gustavoMarquesz commented on propig/src/pages/LoginPage.jsx
> +                    <h2>conecte se</h2>
Okay! ciente.

2023-04-02 01:16 UTC, OTalDoL2 approved these changes
Componentes de Tela ok!

2023-04-04 19:45 UTC, marcosilva2336 approved these changes

2023-04-04 19:46 UTC, marcosilva2336 commented
Tudo ok

2023-04-04 20:34 UTC, merged